### ISSUE TITLE
Feature Request: Option to disable chat between servers

### ISSUE THREAD

**Issue by LatePacket** [Aoi39/VelocityDiscordChatBridge#1]
An option to disable chat between connected Minecraft servers for example if only using the bot for whitelisting and server status etc

**Comment by Aoi39** [comment]
We are not considering adding an option for turning ChatBridge on or off.
This is because ChatBridge is the main function of this plugin.
If you want to disable Chat and enable other notifications, just use version 1.0.2, empty the ChatBridge channel, and set the other.

**Comment by LatePacket** [comment]
I'm not talking about the MC server to discord chat, I mean like MC server 1 to MC server 2 or is that the option you don't want to add? 
I am already using 1.0.2 and have join leave and startup notifications set

Sorry if I'm not clear or confusing

**Comment by Aoi39** [comment]
I guess I was mistaken.
I tried to disable it when I emptied the channel for ChatBridge but forgot.
I'll make some changes to the 1.0.2 file, since it's a bit of a pain to change the version just for this change.

**Comment by LatePacket** [comment]
Sorry for being a pain just trying to provide useful suggestions when I think of them :sweat_smile:

**Comment by Aoi39** [comment]
Don't mind me, I appreciate you giving me thoughts that will make my Plugin better.

**Comment by Aoi39** [comment]
This problem has been corrected in version 1.0.2-2.
[VelocityDiscordChatBridge-1.0.2-2](https://modrinth.com/plugin/velocitydiscordchatbridge/version/EBGTzYVT)

**Comment by LatePacket** [comment]
Thank you I will test it shortly 😄

**Comment by LatePacket** [comment]
Just tested and it's working great thank you :heart:
